# Generated by Django 5.2.4 on 2025-10-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
